slam_toolbox:
  ros__parameters:

    # Multi-robot namespace
    use_namespace: true       # important to separate robots

    # Solver Plugin
    solver_plugin: solver_plugins::CeresSolver
    ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
    ceres_preconditioner: SCHUR_JACOBI
    ceres_trust_strategy: LEVENBERG_MARQUARDT
    ceres_dogleg_type: TRADITIONAL_DOGLEG
    ceres_loss_function: None

    message_filters_queue_size: 30

    # Frame & topic setup
    odom_frame: odom
    # base_frame: laser_frame
    base_frame: base_link

    map_frame: map
    scan_topic: /robot2/scan
    map_topic: /robot2/map
    odom_topic: /robot2/odom

    use_odometry: true
    use_map_saver: true
    mode: mapping

    # Timing and TF
    transform_publish_period: 0.05
    map_update_interval: 1.0
    transform_timeout: 1.0
    tf_buffer_duration: 30.0
    throttle_scans: 1
    stack_size_to_use: 40000000
    debug_logging: false

    # Map resolution and scan range
    resolution: 0.05
    min_laser_range: 0.2
    max_laser_range: 12.0
    minimum_time_interval: 0.2

    # Interactive mode (for RViz pose tools)
    enable_interactive_mode: true

    # Scan matching settings
    use_scan_matching: true
    use_scan_barycenter: false
    minimum_travel_distance: 0.00001
    minimum_travel_heading: 0.00001
    scan_buffer_size: 10
    scan_buffer_maximum_scan_distance: 12.0

    # Matching quality thresholds
    link_match_minimum_response_fine: 0.1
    link_scan_maximum_distance: 10.0

    # Loop closure
    do_loop_closing: true
    loop_match_minimum_chain_size: 5
    loop_match_maximum_variance_coarse: 3.0
    loop_match_minimum_response_coarse: 0.35
    loop_match_minimum_response_fine: 0.45
    loop_search_maximum_distance: 5.0

    # Correlation search windows
    correlation_search_space_dimension: 1.0
    correlation_search_space_resolution: 0.01
    correlation_search_space_smear_deviation: 0.1

    loop_search_space_dimension: 8.0
    loop_search_space_resolution: 0.05
    loop_search_space_smear_deviation: 0.03

    # Scan matcher fine tuning
    distance_variance_penalty: 0.1
    angle_variance_penalty: 0.5
    fine_search_angle_offset: 0.00349
    coarse_search_angle_offset: 0.349
    coarse_angle_resolution: 0.0349
    minimum_angle_penalty: 0.9
    minimum_distance_penalty: 0.5
    use_response_expansion: true
    min_pass_through: 2
    occupancy_threshold: 0.1

    # QoS for multi-robot (ensure PC gets map late subscribers)
    map_publisher_qos:
      durability: transient_local
      reliability: reliable
